services:
  api:
    container_name: api
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/testAPI
    ports:
      - 80:8000
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=testAPI
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
#  redis:
#    image: redis:latest
#    container_name: redis
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

volumes:
  postgres-db:
