"""add creator foreign key

Revision ID: 3adc265b59b8
Revises: a4bb31c8a2ed
Create Date: 2024-10-18 14:25:52.718974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adc265b59b8'
down_revision: Union[str, None] = 'a4bb31c8a2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Products', 'Users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Products', type_='foreignkey')
    op.drop_column('Products', 'creator_id')
    # ### end Alembic commands ###
